from __future__ import annotations

import textwrap
from pathlib import Path

from rtx.scanners.npm import NpmScanner


def test_npm_scanner_reads_pnpm_lock(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    project.mkdir()
    (project / "pnpm-lock.yaml").write_text(
        textwrap.dedent(
            """
            lockfileVersion: 5.4

            specifiers:
              react: ^18.2.0

            dependencies:
              react: 18.2.0

            packages:

              /react/18.2.0:
                resolution: {integrity: sha512-6O2acGY1YLSsmdlL1BcLqrNfbSbEffjIzjOBqAZFt4+TRXMDR9E1fCaeOCfCUDKTgoOFJdvrPaBJayEagAA7oA==}
                engines: {node: '>=0.10.0'}
                dev: false
            """
        ),
        encoding="utf-8",
    )
    scanner = NpmScanner()
    packages = scanner.scan(project)
    assert packages[0].name == "react"
    assert packages[0].version == "18.2.0"


def test_npm_scanner_reads_yarn_lock(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    project.mkdir()
    (project / "yarn.lock").write_text(
        textwrap.dedent(
            '''
            # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
            # yarn lockfile v1


            react@^18.2.0:
              version "18.2.0"
              resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#6b07a9b2c3a3b4d7b9d7b7b7b7b7b7b7b7b7b7b7"
              integrity sha512-6O2acGY1YLSsmdlL1BcLqrNfbSbEffjIzjOBqAZFt4+TRXMDR9E1fCaeOCfCUDKTgoOFJdvrPaBJayEagAA7oA==
            '''
        ),
        encoding="utf-8",
    )
    scanner = NpmScanner()
    packages = scanner.scan(project)
    assert packages[0].name == "react"
    assert packages[0].version == "18.2.0"
